name: services-checker
on:
  pull_request:
    paths:
      - "services/**"
jobs:
  review-service-standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        working-directory: ./services
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      #- name: Unit test coverage
      #  working-directory: ./services
      #  run: go test ./...
